### ISSUE TITLE
Reference Designators on CAN Breakout

### ISSUE THREAD

**Issue by aascalon** [uwrobotics/MarsRover2021-hardware#6]
![image](https://user-images.githubusercontent.com/23003498/93023065-5959c900-f5ba-11ea-84cf-eb3ccd762b77.png)

Please revert the designators back to the default (e.g., D4, D5...). You can have the CAN1_RX stuff, just make it a text instead of refdes.

**Comment by ChristopherA057** [comment]
I fixed the designators and replaced the connectors, could use a quick review before closing the issue
